### ISSUE TITLE
Remove override of createJSModules

### ISSUE THREAD

**Issue by mtebele** [neuberoliveira/react-native-gps-state#2]
The current version of React Native (> 0.47) has removed the createJSModules method in ReactPackage. Therefore any overrides of this method will need to be removed from the library, or this will cause a compilation error.

**Comment by neuberoliveira** [comment]
I build this only for and app build in react 0.45, so i dont event test this in most recent versions.

thanks for the report, i will try to update as soon as possible.

**Comment by mtebele** [comment]
I've created a PR: https://github.com/neuberoliveira/react-native-gps-state/pull/3

**Comment by neuberoliveira** [comment]
Accepted #3
