### ISSUE TITLE
After update to 2.x.x - `isMarshmallowOrAbove` is called on iOS causing app crash

### ISSUE THREAD

**Issue by Simek** [neuberoliveira/react-native-gps-state#20]
After update package from 1.2.1 to 2.x.x (2.0.0 and 2.0.1) function `isMarshmallowOrAbove` is called on iOS causing immediately app crash:
```
Unhandled JS Exception: GPSStateNative.isMarshmallowOrAbove is not a function
```

Unfortunately there is no detailed information or no stack trace included, but I can try help with debugging if such help is needed.

### RNInfo
```
  React Native Environment Info:
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.1 => 16.8.1 
      react-native: 0.58.4 => 0.58.4 
```

**Comment by neuberoliveira** [comment]
Weird one, i am using this plugin right now, on ios simulator, and dont get any crash, anyway thank you, i will fix it as soon as possible.

**Comment by neuberoliveira** [comment]
finally fix this
